# Generated by Django 3.1.2 on 2020-10-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('lattitude', models.DecimalField(decimal_places=15, help_text='Lattitude of the squirrel', max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, help_text='Longitude of the squirrel', max_digits=16)),
                ('unique_squirrel_id', models.CharField(help_text='unique ID of the squirrel', max_length=14, primary_key=True, serialize=False)),
                ('hectare', models.CharField(blank=True, help_text='combination of one axis that runs N-S (01~42) + another axis that runs E-W (A-I)', max_length=3)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='AM or PM', max_length=10)),
                ('Date', models.DateField(blank=True, default=None, help_text='Date when you saw the squirrel', null=True)),
                ('hectare_squirrel_number', models.IntegerField(blank=True, default=0)),
                ('age', models.CharField(choices=[('adult', 'adult'), ('juvenile', 'juvenile'), ('unknown', 'unknown')], help_text='your guess: how old was the squirrel?', max_length=20)),
                ('primary_fur_color', models.CharField(blank=True, choices=[('gray', 'gray'), ('cinnamon', 'cinnamon'), ('black', 'black')], help_text='primary fur color of the squirrel seen', max_length=15)),
                ('highlight_fur_color', models.CharField(blank=True, max_length=20)),
                ('color_notes', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=15)),
                ('specific_location', models.CharField(blank=True, max_length=120)),
                ('running', models.BooleanField(default=False, help_text='Was the squirrel running?')),
                ('chasing', models.BooleanField(default=False, help_text='Was the squirrel chasing something?')),
                ('climbing', models.BooleanField(default=False, help_text='Was the squirrel climbing?')),
                ('eating', models.BooleanField(default=False, help_text='Was the squirrel eating?')),
                ('foraging', models.BooleanField(default=False, help_text='Was the squirrel foraging?')),
                ('other_activities', models.CharField(blank=True, max_length=160)),
                ('kuks', models.BooleanField(default=False, help_text='Squirrel was heard kukking, a chirpy vocal communication used for a variety of reasons.')),
                ('quaas', models.BooleanField(default=False, help_text='Squirrel was heard quaaing, an elongated vocal communication which can indicate the presence of a ground predator such as a dog.')),
                ('moans', models.BooleanField(default=False, help_text='Squirrel was heard moaning, a high-pitched vocal communication which can indicate the presence of an air predator such as a hawk.')),
                ('tail_flags', models.BooleanField(default=False, help_text="Squirrel was seen flagging its tail. Flagging is a whipping motion used to exaggerate squirrel's size and confuse rivals or predators. Looks as if the squirrel is scribbling with tail into the air.")),
                ('tail_twitch', models.BooleanField(default=False, help_text='Squirrel was seen twitching its tail. Looks like a wave running through the tail, like a breakdancer doing the arm wave. Often used to communicate interest, curiosity.')),
                ('approaches', models.BooleanField(default=False, help_text='Squirrel was seen approaching human, seeking food.')),
                ('indifferent', models.BooleanField(default=False, help_text='Squirrel was indifferent to human presence.')),
                ('runs_from', models.BooleanField(default=False, help_text='Squirrel was seen running from humans, seeing them as a threat.')),
                ('other_interactions', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
