# Generated by Django 3.1.2 on 2020-10-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.DecimalField(decimal_places=15, help_text='Lattitude of the squirrel', max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, help_text='Longitude of the squirrel', max_digits=16)),
                ('unique_squirrel_id', models.CharField(help_text='unique ID of the squirrel', max_length=14)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='AM or PM', max_length=10)),
                ('Date', models.DateField(help_text='Date when you saw the squirrel')),
                ('age', models.CharField(choices=[('adult', 'adult'), ('juvenile', 'juvenile'), ('unknown', 'unknown')], help_text='your guess: how old was the squirrel?', max_length=20)),
            ],
        ),
    ]
