# Generated by Django 3.1.2 on 2020-10-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Date',
            new_name='date',
        ),
    ]
