# Generated by Django 3.1.2 on 2020-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='hectare',
            field=models.CharField(blank=True, default=None, help_text='combination of one axis that runs N-S (01~42) + another axis that runs E-W (A-I)', max_length=3),
        ),
    ]
