# Generated by Django 3.1.2 on 2020-10-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201016_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='color_notes',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='hectare',
            field=models.CharField(blank=True, default='', help_text='combination of one axis that runs N-S (01~42) + another axis that runs E-W (A-I)', max_length=3),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='hectare_squirrel_number',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='highlight_fur_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_interactions',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
