# Generated by Django 3.1.2 on 2020-10-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201016_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(choices=[('gray', 'gray'), ('black', 'black'), ('cinnamon', 'cinnamon'), ('unknown', 'unknown')], default='unknown', help_text='Primary fur color of the squirrel', max_length=10),
        ),
    ]
