# Generated by Django 3.1.2 on 2020-10-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20201016_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Date',
            new_name='date',
        ),
    ]
