# Generated by Django 3.1.2 on 2020-10-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20201016_0929'),
        ('sightings', '0003_squirrel_primary_fur_color'),
    ]

    operations = [
    ]
